!> summary:   Manually optimized IxIxAt routines for Intel compilers, NA = 2..33
!> author:    Joerg Stiller, Erik Pfister
!> date:      2020/05/07
!> license:   Institute of Fluid Mechanics, TU Dresden, 01062 Dresden, Germany
!===============================================================================
!
! available variants
! * IxIxAt_01_01_01_01.f
!   IxIxAt_01_01_02_01.f
!   IxIxAt_01_01_41_04.f

! 1:1 operators ----------------------------------------------------------------

#define _NA1_  2
#define _NA2_  2
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  3
#define _NA2_  3
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  4
#define _NA2_  4
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  5
#define _NA2_  5
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  6
#define _NA2_  6
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  7
#define _NA2_  7
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  8
#define _NA2_  8
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  9
#define _NA2_  9
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  10
#define _NA2_  10
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  11
#define _NA2_  11
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  12
#define _NA2_  12
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  13
#define _NA2_  13
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  14
#define _NA2_  14
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  15
#define _NA2_  15
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  16
#define _NA2_  16
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  17
#define _NA2_  17
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  18
#define _NA2_  18
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  19
#define _NA2_  19
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  20
#define _NA2_  20
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  21
#define _NA2_  21
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  22
#define _NA2_  22
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  23
#define _NA2_  23
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  24
#define _NA2_  24
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  25
#define _NA2_  25
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  26
#define _NA2_  26
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  27
#define _NA2_  27
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  28
#define _NA2_  28
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  29
#define _NA2_  29
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  30
#define _NA2_  30
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  31
#define _NA2_  31
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  32
#define _NA2_  32
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  33
#define _NA2_  33
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_


! 1:2 operators ----------------------------------------------------------------

#define _NA1_  2
#define _NA2_  3
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  2
#define _NA2_  4
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  3
#define _NA2_  4
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  3
#define _NA2_  5
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  4
#define _NA2_  8
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  5
#define _NA2_  9
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  8
#define _NA2_  16
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  9
#define _NA2_  17
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  16
#define _NA2_  30
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  17
#define _NA2_  33
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_


! 2:1 operators ----------------------------------------------------------------

#define _NA1_  3
#define _NA2_  2
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  4
#define _NA2_  2
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  4
#define _NA2_  3
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  5
#define _NA2_  3
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  8
#define _NA2_  4
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  9
#define _NA2_  5
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  16
#define _NA2_  8
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  17
#define _NA2_  9
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  30
#define _NA2_  16
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_

#define _NA1_  33
#define _NA2_  17
#include "IxIxAt_01_01_02_01.f"
#undef _NA1_
#undef _NA2_
