!> summary:  3D spectral element vector variable
!> author:   Joerg Stiller
!> date:     2021/11/03
!> license:  Institute of Fluid Mechanics, TU Dresden, 01062 Dresden, Germany
!===============================================================================

module SEM__Vector__3D
  use Kind_Parameters, only: RNP
  use Spectral_Element_Mesh__3D
  use SEM__Variable__3D
  implicit none
  private

  public :: SEM_Vector_3D

  !-----------------------------------------------------------------------------
  !> 3D spectral element vector variable
  !>
  !> This type allows to identify vector variables and provides additional
  !> functionality for them. The variables are assumed to have three components
  !> and can be created using either from scratch, by slicing a spectral element
  !> variable or by wrapping a mesh variable.

  type, extends(SEM_Variable_3D) :: SEM_Vector_3D
  end type SEM_Vector_3D

  ! constructor
  interface SEM_Vector_3D
    module procedure New_Scratch
    module procedure New_Slice
    module procedure New_Wrap
  end interface

contains

  !=============================================================================
  ! Constructors

  !-----------------------------------------------------------------------------
  !> 3D spectral element vector constructor

  function New_Scratch(sem) result(this)
    class(SpectralElementMesh_3D), target, intent(in) :: sem
    type(SEM_Vector_3D) :: this

    call this % Init_SEM_Variable_3D(sem, nc = 3)

  end function New_Scratch

  !-----------------------------------------------------------------------------
  !> New spectral element vector generated from slice

  function New_Slice(sev, first, copy) result(this)
    class(SEM_Variable_3D), target, intent(in)  :: sev
    integer,           intent(in) :: first !< first component of slice
    logical, optional, intent(in) :: copy  !< copy into fresh memory [F]
    type(SEM_Vector_3D) :: this

    call sev % GetSlice(this, first, first+2, copy)

  end function New_Slice

  !-----------------------------------------------------------------------------
  !> New spectral element vector generated by wrapping a vectorial mesh variable

  function New_Wrap(sem, u) result(this)
    class(SpectralElementMesh_3D), target, intent(in) :: sem
    real(RNP), contiguous, target, intent(in) :: u(:,:,:,:,:)
    type(SEM_Vector_3D) :: this

    this % sem                  =>  sem
    this % val(0:,0:,0:,1:,1:)  =>  u(:,:,:,:,:3)

  end function New_Wrap

  !=============================================================================

end module SEM__Vector__3D
