!> summary:  3D spectral element scalar variable
!> author:   Joerg Stiller
!> date:     2021/07/01
!> license:  Institute of Fluid Mechanics, TU Dresden, 01062 Dresden, Germany
!===============================================================================

module Spectral_Element_Scalar__3D
  use Kind_Parameters, only: RNP
  use Spectral_Element_Mesh__3D
  use Spectral_Element_Variable__3D
  implicit none
  private

  public :: SpectralElementScalar_3D

  !-----------------------------------------------------------------------------
  !> 3D spectral element scalar variable
  !>
  !> This type allows to identify scalar variables and provides additional
  !> functionality for them. The variables are assumed to have one component
  !> and can be created using either from scratch, by slicing a spectral element
  !> variable or by wrapping a scalar mesh variable.

  type, extends(SpectralElementVariable_3D) :: SpectralElementScalar_3D
  contains
    procedure :: GetVolumeIntegral
  end type SpectralElementScalar_3D

  ! constructor
  interface SpectralElementScalar_3D
    module procedure New_Scratch
    module procedure New_Slice
    module procedure New_Wrap
  end interface

contains

  !=============================================================================
  ! Constructors

  !-----------------------------------------------------------------------------
  !> New spectral element scalar from scratch

  function New_Scratch(sem) result(this)
    class(SpectralElementMesh_3D), target, intent(in) :: sem
    type(SpectralElementScalar_3D) :: this

    call this % Init_SpectralElementVariable_3D(sem, nc = 1)

  end function New_Scratch

  !-----------------------------------------------------------------------------
  !> New spectral element scalar generated from slice

  function New_Slice(sev, comp, copy) result(this)
    class(SpectralElementVariable_3D), target, intent(in)  :: sev
    integer,           intent(in) :: comp !< selected component
    logical, optional, intent(in) :: copy !< copy into fresh memory [F]
    type(SpectralElementScalar_3D) :: this

    call sev % GetSlice(this, comp, comp, copy)

  end function New_Slice

  !-----------------------------------------------------------------------------
  !> New spectral element scalar generated by wrapping a scalar mesh variable

  function New_Wrap(sem, u) result(this)
    class(SpectralElementMesh_3D), target, intent(in) :: sem
    real(RNP), contiguous, intent(in) :: u(0:,0:,0:,:)
    type(SpectralElementScalar_3D) :: this

    this % sem => sem
    call MapVariable(sem % std_op % po, sem % mesh % n_elem, u, this % val)

  end function New_Wrap

  !=============================================================================
  ! Utilities

  !-----------------------------------------------------------------------------
  !> TBP for computing the volume integral of the scalar
  !>
  !> The otional argument `scope` allows to modify the scope of collective MPI
  !> operations. If it is absent or equal `'parts'`, the latter are restricted
  !> to the active partitions governed by `this%sem%mesh%comm_parts`.
  !> Passing `scope = 'world'` selects `this%sem%mesh%comm_world` and thus
  !> includes the inactive (empty) partitions.

  subroutine GetVolumeIntegral(this, vi, scope)
    class(SpectralElementScalar_3D), intent(in) :: this
    real(RNP), intent(out) :: vi !< volume integral
    character(len=*), optional, intent(in) :: scope !< scope of collect MPI ops

    real(RNP) :: vi_all(1)

    call this % GetVolumeIntegrals(vi_all, scope)
    vi = vi_all(1)

  end subroutine GetVolumeIntegral

  !=============================================================================
  ! Helpers

  !-----------------------------------------------------------------------------
  !> Map scalar to array variable

  subroutine MapVariable(po, ne, s, a)
    integer, intent(in) :: po !< polynomial order
    integer, intent(in) :: ne !< number of elements
    real(RNP), target , intent(in)  :: s((po+1)**3 * ne) !< scalar variable
    real(RNP), pointer, intent(out) :: a(:,:,:,:,:)      !< array variable

    a(0:po,0:po,0:po,1:ne,1:1) => s

  end subroutine MapVariable

  !=============================================================================

end module Spectral_Element_Scalar__3D
