!> summary:   Manually optimized IxBtxI routines for Intel compilers, NB = 2..33
!> author:    Joerg Stiller, Erik Pfister
!> date:      2020/05/07
!> license:   Institute of Fluid Mechanics, TU Dresden, 01062 Dresden, Germany
!===============================================================================
!
! available variants
! * IxBtxI_01_01_01_01.f
!   IxBtxI_01_02_01_01.f
!   IxBtxI_01_04_01_01.f
!   IxBtxI_01_04_01_41.f
!   IxBtxI_01_08_01_01.f

! 1:1 operators ----------------------------------------------------------------

#define _NB1_  2
#define _NB2_  2
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  3
#define _NB2_  3
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  4
#define _NB2_  4
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  5
#define _NB2_  5
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  6
#define _NB2_  6
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  7
#define _NB2_  7
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  8
#define _NB2_  8
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  9
#define _NB2_  9
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  10
#define _NB2_  10
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  11
#define _NB2_  11
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  12
#define _NB2_  12
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  13
#define _NB2_  13
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  14
#define _NB2_  14
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  15
#define _NB2_  15
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  16
#define _NB2_  16
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  17
#define _NB2_  17
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  18
#define _NB2_  18
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  19
#define _NB2_  19
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  20
#define _NB2_  20
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  21
#define _NB2_  21
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  22
#define _NB2_  22
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  23
#define _NB2_  23
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  24
#define _NB2_  24
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  25
#define _NB2_  25
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  26
#define _NB2_  26
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  27
#define _NB2_  27
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  28
#define _NB2_  28
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  29
#define _NB2_  29
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  30
#define _NB2_  30
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  31
#define _NB2_  31
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  32
#define _NB2_  32
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  33
#define _NB2_  33
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_


! 1:2 operators ----------------------------------------------------------------

#define _NB1_  2
#define _NB2_  3
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  2
#define _NB2_  4
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  3
#define _NB2_  4
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  3
#define _NB2_  5
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  4
#define _NB2_  8
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  5
#define _NB2_  9
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  8
#define _NB2_  16
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  9
#define _NB2_  17
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  16
#define _NB2_  30
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  17
#define _NB2_  33
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_


! 2:1 operators ----------------------------------------------------------------

#define _NB1_  3
#define _NB2_  2
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  4
#define _NB2_  2
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  4
#define _NB2_  3
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  5
#define _NB2_  3
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  8
#define _NB2_  4
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  9
#define _NB2_  5
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  16
#define _NB2_  8
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  17
#define _NB2_  9
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  30
#define _NB2_  16
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_

#define _NB1_  33
#define _NB2_  17
#include "IxBtxI_01_01_01_01.f"
#undef _NB1_
#undef _NB2_
